.PHONY: generate generate-proto generate-rest

# The OpenAPI contract lives in WellSpent-proto but does not go through BSR —
# there is no OpenAPI equivalent. That repo is public, so this fetches the raw
# file into the WellSpentREST target, where the swift-openapi-generator build
# plugin picks it up. Override to iterate against an unmerged contract change.
OPENAPI_SPEC ?= https://raw.githubusercontent.com/BeWellSpent/WellSpent-proto/main/openapi/v1/wellspent.yaml
REST_SPEC_PATH := Packages/WellSpentAPI/Sources/WellSpentREST/openapi.yaml

# Both codegen inputs. Neither output is committed — see .gitignore.
generate: generate-proto generate-rest

generate-proto:
	buf generate

# Only fetches. The Swift is generated by the SPM build plugin during the build
# itself, which is why Xcode Cloud needs nothing here beyond this file existing.
generate-rest:
	curl -fsSL "$(OPENAPI_SPEC)" -o "$(REST_SPEC_PATH)"
